site_name: Karnaugh Map Simplification Documentation
theme: readthedocs
pages:
- [index.md]
- [Boolean Algebra.md]
- [Karnaugh Maps.md]
- [Simplification Examples.md]
#- [Computational Simplifier.md]
#- [Software Engineering.md]
#- [Contributing.md]
#- [Troubleshooting.md]